CREATE DATABASE Supermarket;

USE Supermarket;

CREATE TABLE Categories
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(30) NOT NULL
);

CREATE TABLE Items
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(30) NOT NULL,
	Price DECIMAL(15, 2) NOT NULL,
	CategoryId INT FOREIGN KEY REFERENCES [dbo].[Categories]([Id]) NOT NULL
);

CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL,
	Salary DECIMAL(15, 2) NOT NULL
);

CREATE TABLE Orders
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[DateTime] DATETIME NOT NULL,
	EmployeeId INT FOREIGN KEY REFERENCES [dbo].[Employees]([Id]) NOT NULL
);

CREATE TABLE OrderItems
(
	OrderId INT FOREIGN KEY REFERENCES [dbo].[Orders]([Id]) NOT NULL,
	ItemId INT FOREIGN KEY REFERENCES [dbo].[Items]([Id]) NOT NULL,
	Quantity INT NOT NULL CHECK(Quantity >= 1),
	CONSTRAINT PK_OrderItems PRIMARY KEY (OrderId, ItemId)
);

CREATE TABLE Shifts
(
	Id INT IDENTITY NOT NULL,
	EmployeeId INT FOREIGN KEY REFERENCES [dbo].[Employees]([Id]) NOT NULL,
	CheckIn DATETIME NOT NULL,
	CheckOut DATETIME NOT NULL,
	CONSTRAINT CHK_CheckIn CHECK (CheckIn < CheckOut),
	CONSTRAINT PK_Shifts PRIMARY KEY (Id, EmployeeId)
);