CREATE TRIGGER tr_CancelTrips ON [dbo].[Trips] INSTEAD OF DELETE
AS
BEGIN
	UPDATE [Trips]
	   SET
	       [CancelDate] = GETDATE()
	 WHERE [Id] IN (SELECT Id FROM [DELETED] AS d WHERE [CancelDate] IS NULL)
END

DELETE FROM Trips
WHERE Id IN (48, 49, 50)