//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftUniInjector.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vars {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vars() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftUniInjector.Resources.Vars", typeof(Vars).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nqkyf_path.txt.
        /// </summary>
        internal static string SoftUniInjector_Repositories_DefaultSoftUniRepository_dbPath {
            get {
                return ResourceManager.GetString("SoftUniInjector.Repositories.DefaultSoftUniRepository_dbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        internal static string SoftUniInjector_Repositories_DefaultUserRepository_count {
            get {
                return ResourceManager.GetString("SoftUniInjector.Repositories.DefaultUserRepository_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../db/users.txt.
        /// </summary>
        internal static string SoftUniInjector_Services_UserService_dbPath {
            get {
                return ResourceManager.GetString("SoftUniInjector.Services.UserService_dbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03-07-2011.
        /// </summary>
        internal static string SoftUniInjector_Services_UserService_myDateTime {
            get {
                return ResourceManager.GetString("SoftUniInjector.Services.UserService_myDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoYaL.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
