CREATE DATABASE Bitbucket;

USE Bitbucket;

CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Username NVARCHAR(30) NOT NULL,
	[Password] NVARCHAR(30) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
);

CREATE TABLE Repositories
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
);

CREATE TABLE RepositoriesContributors
(
	RepositoryId INT FOREIGN KEY REFERENCES [dbo].[Repositories]([Id]) NOT NULL,
	ContributorId INT FOREIGN KEY REFERENCES [dbo].[Users]([Id]) NOT NULL,
	CONSTRAINT PK_RepositoriesContributors PRIMARY KEY (RepositoryId, ContributorId)
);

CREATE TABLE Issues
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	IssueStatus CHAR(6) NOT NULL,
	RepositoryId INT FOREIGN KEY REFERENCES [dbo].[Repositories]([Id])  NOT NULL,
	AssigneeId INT FOREIGN KEY REFERENCES [dbo].[Users]([Id]) NOT NULL
);

CREATE TABLE Commits
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Message] NVARCHAR(255) NOT NULL,
	IssueId INT FOREIGN KEY REFERENCES [dbo].[Issues]([Id]),
	RepositoryId INT FOREIGN KEY REFERENCES [dbo].[Repositories]([Id]) NOT NULL,
	ContributorId INT FOREIGN KEY REFERENCES [dbo].[Users]([Id]) NOT NULL
);

CREATE TABLE Files
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	Size DECIMAL(15, 2) NOT NULL,
	ParentId INT FOREIGN KEY REFERENCES [dbo].[Files]([Id]),
	CommitId INT FOREIGN KEY REFERENCES [dbo].[Commits]([Id]) NOT NULL
);